name: V2LY actions test

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: Build and push docker container
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2      
    - name: Use Node 12
      uses: actions/setup-node@v1
    - name: Build
      run: ./test
  
      env:
        AWS_ACCOUNT_ID: 585172581592
        AWS_ACCESS_KEY_ID: AKIAYQPYA7TMKZS4NM6W
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
        IMAGE_TAG_VERSION: GITHUB_SHA
